# Generated by Django 5.1.2 on 2026-08-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockbalance',
            options={'ordering': ['item_id', 'warehouse_id']},
        ),
    ]
