# Generated by Django 5.1.2 on 2026-08-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_stockbalance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='quote_lines/'),
        ),
        migrations.CreateModel(
            name='StandardDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='drawings/standard/')),
                ('default_girth', models.CharField(blank=True, max_length=64)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_drawings', to='myApp.itemcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='quotationline',
            name='standard_drawing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='myApp.standarddrawing'),
        ),
    ]
