# Generated by Django 5.1.2 on 2026-08-13 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_item_reference_image_quotationline_custom_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Note'), ('follow_up', 'Follow-up'), ('promise', 'Promise to Pay'), ('dispute', 'Dispute'), ('resolved', 'Resolved')], default='follow_up', max_length=16)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_notes', to='myApp.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
