# Generated by Django 5.1.2 on 2026-08-14 10:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_invoicenote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('dimension', models.CharField(choices=[('profile', 'Profile'), ('gauge', 'Gauge'), ('color', 'Colour')], max_length=10)),
                ('category', models.CharField(max_length=80)),
                ('lm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=16)),
                ('source', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['year', 'dimension', 'category', 'month'],
                'indexes': [models.Index(fields=['year', 'dimension'], name='myApp_produ_year_9fa2e6_idx')],
                'unique_together': {('year', 'month', 'dimension', 'category')},
            },
        ),
    ]
