# Generated by Django 5.1.2 on 2026-08-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_productionactual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionactual',
            name='dimension',
            field=models.CharField(choices=[('profile', 'Profile'), ('gauge', 'Gauge'), ('color', 'Colour'), ('summary', 'Summary')], max_length=10),
        ),
    ]
